"""
SSL & Reverse Proxy Service
=============================
Manages Let's Encrypt certificate issuance, renewal, and Nginx/Traefik
reverse proxy configuration generation. All actual operations are dispatched
via ExecutionEngine → server agent.

ADDITIVE — no modification to existing backup/monitoring code.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timedelta, timezone
from jinja2 import Environment, BaseLoader
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.devops_entities import (
    ReverseProxyConfig,
    SSLCertificate,
    SSLStatus,
)

logger = logging.getLogger(__name__)

# Days before expiry to trigger auto-renewal
SSL_RENEWAL_THRESHOLD_DAYS = 30


NGINX_VHOST_TEMPLATE = """\
# Generated by DevOps Control Plane — do not edit manually
server {
    listen 80;
    server_name {{ domain }};
    {% if ssl_enabled and http_redirect %}
    return 301 https://$host$request_uri;
    {% else %}
    location {{ upstream_path }} {
        proxy_pass http://{{ upstream_host }}:{{ upstream_port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    {% endif %}
}

{% if ssl_enabled %}
server {
    listen 443 ssl http2;
    server_name {{ domain }};

    ssl_certificate     {{ cert_path }};
    ssl_certificate_key {{ key_path }};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    add_header Strict-Transport-Security "max-age=63072000" always;

    location {{ upstream_path }} {
        proxy_pass http://{{ upstream_host }}:{{ upstream_port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400;
    }
}
{% endif %}
"""


class SSLService:

    def get_nginx_config(self, proxy: ReverseProxyConfig, cert: SSLCertificate | None) -> str:
        """Render an Nginx virtual host config from a proxy record + optional cert."""
        env = Environment(loader=BaseLoader())
        tmpl = env.from_string(NGINX_VHOST_TEMPLATE)
        cert_path = cert.cert_pem_path if cert else "/etc/nginx/ssl/cert.pem"
        key_path = cert.key_path if cert else "/etc/nginx/ssl/key.pem"
        return tmpl.render(
            domain=proxy.domain,
            upstream_host=proxy.upstream_host,
            upstream_port=proxy.upstream_port,
            upstream_path=proxy.upstream_path or "/",
            ssl_enabled=proxy.ssl_enabled,
            http_redirect=proxy.http_redirect,
            cert_path=cert_path,
            key_path=key_path,
        )

    def get_certbot_issue_command(
        self,
        domain: str,
        email: str,
        webroot: str = "/var/www/certbot",
        staging: bool = False,
    ) -> str:
        """Returns the certbot command string for the agent's script_run_approved handler."""
        flags = "--staging" if staging else ""
        return (
            f"certbot certonly --webroot -w {webroot} "
            f"-d {domain} --email {email} --agree-tos --no-eff-email "
            f"--non-interactive {flags}"
        )

    def get_certbot_renew_command(self) -> str:
        return "certbot renew --quiet --non-interactive"

    async def get_certificates(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        server_id: uuid.UUID | None = None,
        expiring_within_days: int | None = None,
    ) -> list[SSLCertificate]:
        stmt = select(SSLCertificate).where(
            SSLCertificate.organization_id == organization_id
        )
        if server_id:
            stmt = stmt.where(SSLCertificate.server_id == server_id)
        if expiring_within_days is not None:
            threshold = datetime.now(timezone.utc) + timedelta(days=expiring_within_days)
            stmt = stmt.where(
                SSLCertificate.expires_at <= threshold,
                SSLCertificate.status == SSLStatus.ACTIVE,
                SSLCertificate.auto_renew == True,
            )
        result = await db.execute(stmt.order_by(SSLCertificate.expires_at))
        return list(result.scalars().all())

    async def get_proxy_configs(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        server_id: uuid.UUID | None = None,
    ) -> list[ReverseProxyConfig]:
        stmt = select(ReverseProxyConfig).where(
            ReverseProxyConfig.organization_id == organization_id
        )
        if server_id:
            stmt = stmt.where(ReverseProxyConfig.server_id == server_id)
        result = await db.execute(stmt.order_by(ReverseProxyConfig.domain))
        return list(result.scalars().all())

    async def create_certificate_record(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        server_id: uuid.UUID,
        domain: str,
        acme_email: str,
        san_domains: list[str] | None = None,
        auto_renew: bool = True,
    ) -> SSLCertificate:
        cert = SSLCertificate(
            organization_id=organization_id,
            server_id=server_id,
            domain=domain,
            san_domains=san_domains,
            acme_email=acme_email,
            auto_renew=auto_renew,
            status=SSLStatus.PENDING,
        )
        db.add(cert)
        await db.commit()
        await db.refresh(cert)
        return cert

    async def create_proxy_config(
        self,
        db: AsyncSession,
        *,
        organization_id: uuid.UUID,
        server_id: uuid.UUID,
        domain: str,
        upstream_host: str,
        upstream_port: int,
        upstream_path: str = "/",
        ssl_enabled: bool = True,
        http_redirect: bool = True,
        ssl_cert_id: uuid.UUID | None = None,
        proxy_type: str = "nginx",
        linked_plugin_id: str | None = None,
    ) -> ReverseProxyConfig:
        proxy = ReverseProxyConfig(
            organization_id=organization_id,
            server_id=server_id,
            ssl_cert_id=ssl_cert_id,
            proxy_type=proxy_type,
            domain=domain,
            upstream_host=upstream_host,
            upstream_port=upstream_port,
            upstream_path=upstream_path,
            ssl_enabled=ssl_enabled,
            http_redirect=http_redirect,
            linked_plugin_id=linked_plugin_id,
        )
        db.add(proxy)
        await db.commit()
        await db.refresh(proxy)
        return proxy


ssl_service = SSLService()
